/* tslint:disable */
/* eslint-disable */
/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AddressClaimSet
 */
export interface AddressClaimSet {
  /**
   *
   * @type {string}
   * @memberof AddressClaimSet
   */
  country?: string;
  /**
   *
   * @type {string}
   * @memberof AddressClaimSet
   */
  formatted?: string;
  /**
   *
   * @type {string}
   * @memberof AddressClaimSet
   */
  locality?: string;
  /**
   *
   * @type {string}
   * @memberof AddressClaimSet
   */
  postal_code?: string;
  /**
   *
   * @type {string}
   * @memberof AddressClaimSet
   */
  region?: string;
  /**
   *
   * @type {string}
   * @memberof AddressClaimSet
   */
  street_address?: string;
}
