/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConfigPropertyRepresentation } from './configPropertyRepresentation';

export class AuthenticatorConfigInfoRepresentation {
  'helpText'?: string;
  'name'?: string;
  'properties'?: Array<ConfigPropertyRepresentation>;
  'providerId'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'helpText',
      baseName: 'helpText',
      type: 'string',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
    },
    {
      name: 'properties',
      baseName: 'properties',
      type: 'Array<ConfigPropertyRepresentation>',
    },
    {
      name: 'providerId',
      baseName: 'providerId',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return AuthenticatorConfigInfoRepresentation.attributeTypeMap;
  }
}
