/* tslint:disable */
/* eslint-disable */
/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AuthenticationExecutionExportRepresentation
 */
export interface AuthenticationExecutionExportRepresentation {
  /**
   *
   * @type {string}
   * @memberof AuthenticationExecutionExportRepresentation
   */
  authenticator?: string;
  /**
   *
   * @type {string}
   * @memberof AuthenticationExecutionExportRepresentation
   */
  authenticatorConfig?: string;
  /**
   *
   * @type {boolean}
   * @memberof AuthenticationExecutionExportRepresentation
   */
  authenticatorFlow?: boolean;
  /**
   *
   * @type {string}
   * @memberof AuthenticationExecutionExportRepresentation
   */
  flowAlias?: string;
  /**
   *
   * @type {number}
   * @memberof AuthenticationExecutionExportRepresentation
   */
  priority?: number;
  /**
   *
   * @type {string}
   * @memberof AuthenticationExecutionExportRepresentation
   */
  requirement?: string;
  /**
   *
   * @type {boolean}
   * @memberof AuthenticationExecutionExportRepresentation
   */
  userSetupAllowed?: boolean;
}
