/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CertificateRepresentation {
  'certificate'?: string;
  'kid'?: string;
  'privateKey'?: string;
  'publicKey'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'certificate',
      baseName: 'certificate',
      type: 'string',
    },
    {
      name: 'kid',
      baseName: 'kid',
      type: 'string',
    },
    {
      name: 'privateKey',
      baseName: 'privateKey',
      type: 'string',
    },
    {
      name: 'publicKey',
      baseName: 'publicKey',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return CertificateRepresentation.attributeTypeMap;
  }
}
