/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProtocolMapperRepresentation } from './protocolMapperRepresentation';

export class ClientScopeRepresentation {
  'attributes'?: { [key: string]: any };
  'description'?: string;
  'id'?: string;
  'name'?: string;
  'protocol'?: string;
  'protocolMappers'?: Array<ProtocolMapperRepresentation>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'attributes',
      baseName: 'attributes',
      type: '{ [key: string]: any; }',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'string',
    },
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
    },
    {
      name: 'protocol',
      baseName: 'protocol',
      type: 'string',
    },
    {
      name: 'protocolMappers',
      baseName: 'protocolMappers',
      type: 'Array<ProtocolMapperRepresentation>',
    },
  ];

  static getAttributeTypeMap() {
    return ClientScopeRepresentation.attributeTypeMap;
  }
}
