/* tslint:disable */
/* eslint-disable */
/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ClientInitialAccessPresentation
 */
export interface ClientInitialAccessPresentation {
  /**
   *
   * @type {number}
   * @memberof ClientInitialAccessPresentation
   */
  count?: number;
  /**
   *
   * @type {number}
   * @memberof ClientInitialAccessPresentation
   */
  expiration?: number;
  /**
   *
   * @type {string}
   * @memberof ClientInitialAccessPresentation
   */
  id?: string;
  /**
   *
   * @type {number}
   * @memberof ClientInitialAccessPresentation
   */
  remainingCount?: number;
  /**
   *
   * @type {number}
   * @memberof ClientInitialAccessPresentation
   */
  timestamp?: number;
  /**
   *
   * @type {string}
   * @memberof ClientInitialAccessPresentation
   */
  token?: string;
}
