/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CredentialRepresentation {
  'createdDate'?: number;
  'credentialData'?: string;
  'id'?: string;
  'priority'?: number;
  'secretData'?: string;
  'temporary'?: boolean;
  'type'?: string;
  'userLabel'?: string;
  'value'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'createdDate',
      baseName: 'createdDate',
      type: 'number',
    },
    {
      name: 'credentialData',
      baseName: 'credentialData',
      type: 'string',
    },
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'priority',
      baseName: 'priority',
      type: 'number',
    },
    {
      name: 'secretData',
      baseName: 'secretData',
      type: 'string',
    },
    {
      name: 'temporary',
      baseName: 'temporary',
      type: 'boolean',
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'string',
    },
    {
      name: 'userLabel',
      baseName: 'userLabel',
      type: 'string',
    },
    {
      name: 'value',
      baseName: 'value',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return CredentialRepresentation.attributeTypeMap;
  }
}
