/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class JsonNode {
  'array'?: boolean;
  'bigDecimal'?: boolean;
  'bigInteger'?: boolean;
  'binary'?: boolean;
  '_boolean'?: boolean;
  'containerNode'?: boolean;
  '_double'?: boolean;
  'empty'?: boolean;
  '_float'?: boolean;
  'floatingPointNumber'?: boolean;
  '_int'?: boolean;
  'integralNumber'?: boolean;
  '_long'?: boolean;
  'missingNode'?: boolean;
  'nodeType'?: JsonNode.NodeTypeEnum;
  '_null'?: boolean;
  'number'?: boolean;
  'object'?: boolean;
  'pojo'?: boolean;
  '_short'?: boolean;
  'textual'?: boolean;
  'valueNode'?: boolean;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'array',
      baseName: 'array',
      type: 'boolean',
    },
    {
      name: 'bigDecimal',
      baseName: 'bigDecimal',
      type: 'boolean',
    },
    {
      name: 'bigInteger',
      baseName: 'bigInteger',
      type: 'boolean',
    },
    {
      name: 'binary',
      baseName: 'binary',
      type: 'boolean',
    },
    {
      name: '_boolean',
      baseName: 'boolean',
      type: 'boolean',
    },
    {
      name: 'containerNode',
      baseName: 'containerNode',
      type: 'boolean',
    },
    {
      name: '_double',
      baseName: 'double',
      type: 'boolean',
    },
    {
      name: 'empty',
      baseName: 'empty',
      type: 'boolean',
    },
    {
      name: '_float',
      baseName: 'float',
      type: 'boolean',
    },
    {
      name: 'floatingPointNumber',
      baseName: 'floatingPointNumber',
      type: 'boolean',
    },
    {
      name: '_int',
      baseName: 'int',
      type: 'boolean',
    },
    {
      name: 'integralNumber',
      baseName: 'integralNumber',
      type: 'boolean',
    },
    {
      name: '_long',
      baseName: 'long',
      type: 'boolean',
    },
    {
      name: 'missingNode',
      baseName: 'missingNode',
      type: 'boolean',
    },
    {
      name: 'nodeType',
      baseName: 'nodeType',
      type: 'JsonNode.NodeTypeEnum',
    },
    {
      name: '_null',
      baseName: 'null',
      type: 'boolean',
    },
    {
      name: 'number',
      baseName: 'number',
      type: 'boolean',
    },
    {
      name: 'object',
      baseName: 'object',
      type: 'boolean',
    },
    {
      name: 'pojo',
      baseName: 'pojo',
      type: 'boolean',
    },
    {
      name: '_short',
      baseName: 'short',
      type: 'boolean',
    },
    {
      name: 'textual',
      baseName: 'textual',
      type: 'boolean',
    },
    {
      name: 'valueNode',
      baseName: 'valueNode',
      type: 'boolean',
    },
  ];

  static getAttributeTypeMap() {
    return JsonNode.attributeTypeMap;
  }
}

export namespace JsonNode {
  export enum NodeTypeEnum {
    Array = <any>'ARRAY',
    Binary = <any>'BINARY',
    Boolean = <any>'BOOLEAN',
    Missing = <any>'MISSING',
    Null = <any>'NULL',
    Number = <any>'NUMBER',
    Object = <any>'OBJECT',
    Pojo = <any>'POJO',
    String = <any>'STRING',
  }
}
