/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class KeyStoreConfig {
  'format'?: string;
  'keyAlias'?: string;
  'keyPassword'?: string;
  'realmAlias'?: string;
  'realmCertificate'?: boolean;
  'storePassword'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'format',
      baseName: 'format',
      type: 'string',
    },
    {
      name: 'keyAlias',
      baseName: 'keyAlias',
      type: 'string',
    },
    {
      name: 'keyPassword',
      baseName: 'keyPassword',
      type: 'string',
    },
    {
      name: 'realmAlias',
      baseName: 'realmAlias',
      type: 'string',
    },
    {
      name: 'realmCertificate',
      baseName: 'realmCertificate',
      type: 'boolean',
    },
    {
      name: 'storePassword',
      baseName: 'storePassword',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return KeyStoreConfig.attributeTypeMap;
  }
}
