/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { KeysMetadataRepresentationKeyMetadataRepresentation } from './keysMetadataRepresentationKeyMetadataRepresentation';

export class KeysMetadataRepresentation {
  'active'?: { [key: string]: any };
  'keys'?: Array<KeysMetadataRepresentationKeyMetadataRepresentation>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'active',
      baseName: 'active',
      type: '{ [key: string]: any; }',
    },
    {
      name: 'keys',
      baseName: 'keys',
      type: 'Array<KeysMetadataRepresentationKeyMetadataRepresentation>',
    },
  ];

  static getAttributeTypeMap() {
    return KeysMetadataRepresentation.attributeTypeMap;
  }
}
