/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MultivaluedHashMap {
  'empty'?: boolean;
  'loadFactor'?: number;
  'threshold'?: number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'empty',
      baseName: 'empty',
      type: 'boolean',
    },
    {
      name: 'loadFactor',
      baseName: 'loadFactor',
      type: 'number',
    },
    {
      name: 'threshold',
      baseName: 'threshold',
      type: 'number',
    },
  ];

  static getAttributeTypeMap() {
    return MultivaluedHashMap.attributeTypeMap;
  }
}
