/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ClientRepresentation } from './clientRepresentation';
import { GroupRepresentation } from './groupRepresentation';
import { IdentityProviderMapperRepresentation } from './identityProviderMapperRepresentation';
import { IdentityProviderRepresentation } from './identityProviderRepresentation';
import { RolesRepresentation } from './rolesRepresentation';
import { UserRepresentation } from './userRepresentation';

export class PartialImportRepresentation {
  'clients'?: Array<ClientRepresentation>;
  'groups'?: Array<GroupRepresentation>;
  'identityProviderMappers'?: Array<IdentityProviderMapperRepresentation>;
  'identityProviders'?: Array<IdentityProviderRepresentation>;
  'ifResourceExists'?: string;
  'policy'?: PartialImportRepresentation.PolicyEnum;
  'roles'?: RolesRepresentation;
  'users'?: Array<UserRepresentation>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'clients',
      baseName: 'clients',
      type: 'Array<ClientRepresentation>',
    },
    {
      name: 'groups',
      baseName: 'groups',
      type: 'Array<GroupRepresentation>',
    },
    {
      name: 'identityProviderMappers',
      baseName: 'identityProviderMappers',
      type: 'Array<IdentityProviderMapperRepresentation>',
    },
    {
      name: 'identityProviders',
      baseName: 'identityProviders',
      type: 'Array<IdentityProviderRepresentation>',
    },
    {
      name: 'ifResourceExists',
      baseName: 'ifResourceExists',
      type: 'string',
    },
    {
      name: 'policy',
      baseName: 'policy',
      type: 'PartialImportRepresentation.PolicyEnum',
    },
    {
      name: 'roles',
      baseName: 'roles',
      type: 'RolesRepresentation',
    },
    {
      name: 'users',
      baseName: 'users',
      type: 'Array<UserRepresentation>',
    },
  ];

  static getAttributeTypeMap() {
    return PartialImportRepresentation.attributeTypeMap;
  }
}

export namespace PartialImportRepresentation {
  export enum PolicyEnum {
    Skip = <any>'SKIP',
    Overwrite = <any>'OVERWRITE',
    Fail = <any>'FAIL',
  }
}
