/* tslint:disable */
/* eslint-disable */
/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PasswordPolicyTypeRepresentation
 */
export interface PasswordPolicyTypeRepresentation {
  /**
   *
   * @type {string}
   * @memberof PasswordPolicyTypeRepresentation
   */
  configType?: string;
  /**
   *
   * @type {string}
   * @memberof PasswordPolicyTypeRepresentation
   */
  defaultValue?: string;
  /**
   *
   * @type {string}
   * @memberof PasswordPolicyTypeRepresentation
   */
  displayName?: string;
  /**
   *
   * @type {string}
   * @memberof PasswordPolicyTypeRepresentation
   */
  id?: string;
  /**
   *
   * @type {boolean}
   * @memberof PasswordPolicyTypeRepresentation
   */
  multipleSupported?: boolean;
}
