/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ProfileInfoRepresentation {
  'disabledFeatures'?: Array<string>;
  'experimentalFeatures'?: Array<string>;
  'name'?: string;
  'previewFeatures'?: Array<string>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'disabledFeatures',
      baseName: 'disabledFeatures',
      type: 'Array<string>',
    },
    {
      name: 'experimentalFeatures',
      baseName: 'experimentalFeatures',
      type: 'Array<string>',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
    },
    {
      name: 'previewFeatures',
      baseName: 'previewFeatures',
      type: 'Array<string>',
    },
  ];

  static getAttributeTypeMap() {
    return ProfileInfoRepresentation.attributeTypeMap;
  }
}
