/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ProviderRepresentation {
  'operationalInfo'?: { [key: string]: any };
  'order'?: number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'operationalInfo',
      baseName: 'operationalInfo',
      type: '{ [key: string]: any; }',
    },
    {
      name: 'order',
      baseName: 'order',
      type: 'number',
    },
  ];

  static getAttributeTypeMap() {
    return ProviderRepresentation.attributeTypeMap;
  }
}
