/* tslint:disable */
/* eslint-disable */
/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RealmEventsConfigRepresentation
 */
export interface RealmEventsConfigRepresentation {
  /**
   *
   * @type {boolean}
   * @memberof RealmEventsConfigRepresentation
   */
  adminEventsDetailsEnabled?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof RealmEventsConfigRepresentation
   */
  adminEventsEnabled?: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof RealmEventsConfigRepresentation
   */
  enabledEventTypes?: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof RealmEventsConfigRepresentation
   */
  eventsEnabled?: boolean;
  /**
   *
   * @type {number}
   * @memberof RealmEventsConfigRepresentation
   */
  eventsExpiration?: number;
  /**
   *
   * @type {Array<string>}
   * @memberof RealmEventsConfigRepresentation
   */
  eventsListeners?: Array<string>;
}
