/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RoleRepresentation } from './roleRepresentation';

export class RolesRepresentation {
  'client'?: { [key: string]: any };
  'realm'?: Array<RoleRepresentation>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'client',
      baseName: 'client',
      type: '{ [key: string]: any; }',
    },
    {
      name: 'realm',
      baseName: 'realm',
      type: 'Array<RoleRepresentation>',
    },
  ];

  static getAttributeTypeMap() {
    return RolesRepresentation.attributeTypeMap;
  }
}
