/* tslint:disable */
/* eslint-disable */
/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ScopeMappingRepresentation
 */
export interface ScopeMappingRepresentation {
  /**
   *
   * @type {string}
   * @memberof ScopeMappingRepresentation
   */
  client?: string;
  /**
   *
   * @type {string}
   * @memberof ScopeMappingRepresentation
   */
  clientScope?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof ScopeMappingRepresentation
   */
  roles?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof ScopeMappingRepresentation
   */
  self?: string;
}
