/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SystemInfoRepresentation {
  'fileEncoding'?: string;
  'javaHome'?: string;
  'javaRuntime'?: string;
  'javaVendor'?: string;
  'javaVersion'?: string;
  'javaVm'?: string;
  'javaVmVersion'?: string;
  'osArchitecture'?: string;
  'osName'?: string;
  'osVersion'?: string;
  'serverTime'?: string;
  'uptime'?: string;
  'uptimeMillis'?: number;
  'userDir'?: string;
  'userLocale'?: string;
  'userName'?: string;
  'userTimezone'?: string;
  'version'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'fileEncoding',
      baseName: 'fileEncoding',
      type: 'string',
    },
    {
      name: 'javaHome',
      baseName: 'javaHome',
      type: 'string',
    },
    {
      name: 'javaRuntime',
      baseName: 'javaRuntime',
      type: 'string',
    },
    {
      name: 'javaVendor',
      baseName: 'javaVendor',
      type: 'string',
    },
    {
      name: 'javaVersion',
      baseName: 'javaVersion',
      type: 'string',
    },
    {
      name: 'javaVm',
      baseName: 'javaVm',
      type: 'string',
    },
    {
      name: 'javaVmVersion',
      baseName: 'javaVmVersion',
      type: 'string',
    },
    {
      name: 'osArchitecture',
      baseName: 'osArchitecture',
      type: 'string',
    },
    {
      name: 'osName',
      baseName: 'osName',
      type: 'string',
    },
    {
      name: 'osVersion',
      baseName: 'osVersion',
      type: 'string',
    },
    {
      name: 'serverTime',
      baseName: 'serverTime',
      type: 'string',
    },
    {
      name: 'uptime',
      baseName: 'uptime',
      type: 'string',
    },
    {
      name: 'uptimeMillis',
      baseName: 'uptimeMillis',
      type: 'number',
    },
    {
      name: 'userDir',
      baseName: 'userDir',
      type: 'string',
    },
    {
      name: 'userLocale',
      baseName: 'userLocale',
      type: 'string',
    },
    {
      name: 'userName',
      baseName: 'userName',
      type: 'string',
    },
    {
      name: 'userTimezone',
      baseName: 'userTimezone',
      type: 'string',
    },
    {
      name: 'version',
      baseName: 'version',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return SystemInfoRepresentation.attributeTypeMap;
  }
}
