/* tslint:disable */
/* eslint-disable */
/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserFederationProviderRepresentation
 */
export interface UserFederationProviderRepresentation {
  /**
   *
   * @type {number}
   * @memberof UserFederationProviderRepresentation
   */
  changedSyncPeriod?: number;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof UserFederationProviderRepresentation
   */
  config?: { [key: string]: any };
  /**
   *
   * @type {string}
   * @memberof UserFederationProviderRepresentation
   */
  displayName?: string;
  /**
   *
   * @type {number}
   * @memberof UserFederationProviderRepresentation
   */
  fullSyncPeriod?: number;
  /**
   *
   * @type {string}
   * @memberof UserFederationProviderRepresentation
   */
  id?: string;
  /**
   *
   * @type {number}
   * @memberof UserFederationProviderRepresentation
   */
  lastSync?: number;
  /**
   *
   * @type {number}
   * @memberof UserFederationProviderRepresentation
   */
  priority?: number;
  /**
   *
   * @type {string}
   * @memberof UserFederationProviderRepresentation
   */
  providerName?: string;
}
