/* tslint:disable */
/* eslint-disable */
/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from 'url';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from '../base';
// @ts-ignore
import { ClientScopeRepresentation } from '../model';
/**
 * ClientScopesApi - axios parameter creator
 * @export
 */
export const ClientScopesApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @summary Get client scopes belonging to the realm   Returns a list of client scopes belonging to the realm
     * @param {string} realm realm name (not id!)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    realmClientScopesGet: async (
      realm: string,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'realm' is not null or undefined
      assertParamExists('realmClientScopesGet', 'realm', realm);
      const localVarPath = `/{realm}/client-scopes`.replace(
        `{${'realm'}}`,
        encodeURIComponent(String(realm))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication access_token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Delete the client scope
     * @param {string} realm realm name (not id!)
     * @param {string} id id of client scope (not name)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    realmClientScopesIdDelete: async (
      realm: string,
      id: string,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'realm' is not null or undefined
      assertParamExists('realmClientScopesIdDelete', 'realm', realm);
      // verify required parameter 'id' is not null or undefined
      assertParamExists('realmClientScopesIdDelete', 'id', id);
      const localVarPath = `/{realm}/client-scopes/{id}`
        .replace(`{${'realm'}}`, encodeURIComponent(String(realm)))
        .replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'DELETE',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication access_token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get representation of the client scope
     * @param {string} realm realm name (not id!)
     * @param {string} id id of client scope (not name)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    realmClientScopesIdGet: async (
      realm: string,
      id: string,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'realm' is not null or undefined
      assertParamExists('realmClientScopesIdGet', 'realm', realm);
      // verify required parameter 'id' is not null or undefined
      assertParamExists('realmClientScopesIdGet', 'id', id);
      const localVarPath = `/{realm}/client-scopes/{id}`
        .replace(`{${'realm'}}`, encodeURIComponent(String(realm)))
        .replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication access_token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Update the client scope
     * @param {string} realm realm name (not id!)
     * @param {string} id id of client scope (not name)
     * @param {ClientScopeRepresentation} clientScopeRepresentation
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    realmClientScopesIdPut: async (
      realm: string,
      id: string,
      clientScopeRepresentation: ClientScopeRepresentation,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'realm' is not null or undefined
      assertParamExists('realmClientScopesIdPut', 'realm', realm);
      // verify required parameter 'id' is not null or undefined
      assertParamExists('realmClientScopesIdPut', 'id', id);
      // verify required parameter 'clientScopeRepresentation' is not null or undefined
      assertParamExists(
        'realmClientScopesIdPut',
        'clientScopeRepresentation',
        clientScopeRepresentation
      );
      const localVarPath = `/{realm}/client-scopes/{id}`
        .replace(`{${'realm'}}`, encodeURIComponent(String(realm)))
        .replace(`{${'id'}}`, encodeURIComponent(String(id)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'PUT',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication access_token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        clientScopeRepresentation,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Create a new client scope   Client Scope’s name must be unique!
     * @param {string} realm realm name (not id!)
     * @param {ClientScopeRepresentation} clientScopeRepresentation
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    realmClientScopesPost: async (
      realm: string,
      clientScopeRepresentation: ClientScopeRepresentation,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'realm' is not null or undefined
      assertParamExists('realmClientScopesPost', 'realm', realm);
      // verify required parameter 'clientScopeRepresentation' is not null or undefined
      assertParamExists(
        'realmClientScopesPost',
        'clientScopeRepresentation',
        clientScopeRepresentation
      );
      const localVarPath = `/{realm}/client-scopes`.replace(
        `{${'realm'}}`,
        encodeURIComponent(String(realm))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication access_token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        clientScopeRepresentation,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ClientScopesApi - functional programming interface
 * @export
 */
export const ClientScopesApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    ClientScopesApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Get client scopes belonging to the realm   Returns a list of client scopes belonging to the realm
     * @param {string} realm realm name (not id!)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async realmClientScopesGet(
      realm: string,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<{ [key: string]: any }>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.realmClientScopesGet(realm, options);
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @summary Delete the client scope
     * @param {string} realm realm name (not id!)
     * @param {string} id id of client scope (not name)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async realmClientScopesIdDelete(
      realm: string,
      id: string,
      options?: AxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.realmClientScopesIdDelete(
          realm,
          id,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @summary Get representation of the client scope
     * @param {string} realm realm name (not id!)
     * @param {string} id id of client scope (not name)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async realmClientScopesIdGet(
      realm: string,
      id: string,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<ClientScopeRepresentation>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.realmClientScopesIdGet(
          realm,
          id,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @summary Update the client scope
     * @param {string} realm realm name (not id!)
     * @param {string} id id of client scope (not name)
     * @param {ClientScopeRepresentation} clientScopeRepresentation
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async realmClientScopesIdPut(
      realm: string,
      id: string,
      clientScopeRepresentation: ClientScopeRepresentation,
      options?: AxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.realmClientScopesIdPut(
          realm,
          id,
          clientScopeRepresentation,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @summary Create a new client scope   Client Scope’s name must be unique!
     * @param {string} realm realm name (not id!)
     * @param {ClientScopeRepresentation} clientScopeRepresentation
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async realmClientScopesPost(
      realm: string,
      clientScopeRepresentation: ClientScopeRepresentation,
      options?: AxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.realmClientScopesPost(
          realm,
          clientScopeRepresentation,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
  };
};

/**
 * ClientScopesApi - factory interface
 * @export
 */
export const ClientScopesApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = ClientScopesApiFp(configuration);
  return {
    /**
     *
     * @summary Get client scopes belonging to the realm   Returns a list of client scopes belonging to the realm
     * @param {string} realm realm name (not id!)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    realmClientScopesGet(
      realm: string,
      options?: any
    ): AxiosPromise<Array<{ [key: string]: any }>> {
      return localVarFp
        .realmClientScopesGet(realm, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Delete the client scope
     * @param {string} realm realm name (not id!)
     * @param {string} id id of client scope (not name)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    realmClientScopesIdDelete(
      realm: string,
      id: string,
      options?: any
    ): AxiosPromise<void> {
      return localVarFp
        .realmClientScopesIdDelete(realm, id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get representation of the client scope
     * @param {string} realm realm name (not id!)
     * @param {string} id id of client scope (not name)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    realmClientScopesIdGet(
      realm: string,
      id: string,
      options?: any
    ): AxiosPromise<ClientScopeRepresentation> {
      return localVarFp
        .realmClientScopesIdGet(realm, id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Update the client scope
     * @param {string} realm realm name (not id!)
     * @param {string} id id of client scope (not name)
     * @param {ClientScopeRepresentation} clientScopeRepresentation
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    realmClientScopesIdPut(
      realm: string,
      id: string,
      clientScopeRepresentation: ClientScopeRepresentation,
      options?: any
    ): AxiosPromise<void> {
      return localVarFp
        .realmClientScopesIdPut(realm, id, clientScopeRepresentation, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Create a new client scope   Client Scope’s name must be unique!
     * @param {string} realm realm name (not id!)
     * @param {ClientScopeRepresentation} clientScopeRepresentation
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    realmClientScopesPost(
      realm: string,
      clientScopeRepresentation: ClientScopeRepresentation,
      options?: any
    ): AxiosPromise<void> {
      return localVarFp
        .realmClientScopesPost(realm, clientScopeRepresentation, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * ClientScopesApi - object-oriented interface
 * @export
 * @class ClientScopesApi
 * @extends {BaseAPI}
 */
export class ClientScopesApi extends BaseAPI {
  /**
   *
   * @summary Get client scopes belonging to the realm   Returns a list of client scopes belonging to the realm
   * @param {string} realm realm name (not id!)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ClientScopesApi
   */
  public realmClientScopesGet(realm: string, options?: AxiosRequestConfig) {
    return ClientScopesApiFp(this.configuration)
      .realmClientScopesGet(realm, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Delete the client scope
   * @param {string} realm realm name (not id!)
   * @param {string} id id of client scope (not name)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ClientScopesApi
   */
  public realmClientScopesIdDelete(
    realm: string,
    id: string,
    options?: AxiosRequestConfig
  ) {
    return ClientScopesApiFp(this.configuration)
      .realmClientScopesIdDelete(realm, id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get representation of the client scope
   * @param {string} realm realm name (not id!)
   * @param {string} id id of client scope (not name)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ClientScopesApi
   */
  public realmClientScopesIdGet(
    realm: string,
    id: string,
    options?: AxiosRequestConfig
  ) {
    return ClientScopesApiFp(this.configuration)
      .realmClientScopesIdGet(realm, id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Update the client scope
   * @param {string} realm realm name (not id!)
   * @param {string} id id of client scope (not name)
   * @param {ClientScopeRepresentation} clientScopeRepresentation
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ClientScopesApi
   */
  public realmClientScopesIdPut(
    realm: string,
    id: string,
    clientScopeRepresentation: ClientScopeRepresentation,
    options?: AxiosRequestConfig
  ) {
    return ClientScopesApiFp(this.configuration)
      .realmClientScopesIdPut(realm, id, clientScopeRepresentation, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Create a new client scope   Client Scope’s name must be unique!
   * @param {string} realm realm name (not id!)
   * @param {ClientScopeRepresentation} clientScopeRepresentation
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ClientScopesApi
   */
  public realmClientScopesPost(
    realm: string,
    clientScopeRepresentation: ClientScopeRepresentation,
    options?: AxiosRequestConfig
  ) {
    return ClientScopesApiFp(this.configuration)
      .realmClientScopesPost(realm, clientScopeRepresentation, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
