/* eslint-disable */
/**
 * This file was automatically generated by `npm run gendef`.
 * DO NOT MODIFY IT BY HAND. Instead, update the script gendef within package.json,
 * and run `npm run gendef` to regenerate this file.
 */

export interface AddressClaimSet {
  country?: string;
  formatted?: string;
  locality?: string;
  postal_code?: string;
  region?: string;
  street_address?: string;
}
