/* eslint-disable */
/**
 * This file was automatically generated by `npm run gendef`.
 * DO NOT MODIFY IT BY HAND. Instead, update the script gendef within package.json,
 * and run `npm run gendef` to regenerate this file.
 */

export interface AuthenticationExecutionInfoRepresentation {
  alias?: string;
  authenticationConfig?: string;
  authenticationFlow?: boolean;
  configurable?: boolean;
  description?: string;
  displayName?: string;
  flowId?: string;
  id?: string;
  index?: number;
  level?: number;
  providerId?: string;
  requirement?: string;
  requirementChoices?: string[];
}
