/* eslint-disable */
/**
 * This file was automatically generated by `npm run gendef`.
 * DO NOT MODIFY IT BY HAND. Instead, update the script gendef within package.json,
 * and run `npm run gendef` to regenerate this file.
 */

export interface IDToken {
  acr?: string;
  address?: AddressClaimSet;
  at_hash?: string;
  auth_time?: number;
  azp?: string;
  birthdate?: string;
  c_hash?: string;
  category?: "INTERNAL" | "ACCESS" | "ID" | "ADMIN" | "USERINFO" | "LOGOUT" | "AUTHORIZATION_RESPONSE";
  claims_locales?: string;
  email?: string;
  email_verified?: boolean;
  exp?: number;
  family_name?: string;
  gender?: string;
  given_name?: string;
  iat?: number;
  iss?: string;
  jti?: string;
  locale?: string;
  middle_name?: string;
  name?: string;
  nbf?: number;
  nickname?: string;
  nonce?: string;
  otherClaims?: {
    [k: string]: string;
  };
  phone_number?: string;
  phone_number_verified?: boolean;
  picture?: string;
  preferred_username?: string;
  profile?: string;
  s_hash?: string;
  session_state?: string;
  sid?: string;
  sub?: string;
  typ?: string;
  updated_at?: number;
  website?: string;
  zoneinfo?: string;
}
export interface AddressClaimSet {
  country?: string;
  formatted?: string;
  locality?: string;
  postal_code?: string;
  region?: string;
  street_address?: string;
}
